const ingredients = [
    { "ingredientName": "Помидор" },
    { "ingredientName": "Соль" },
    { "ingredientName": "Чиабатта" },
    { "ingredientName": "Оливковое масло" },
    { "ingredientName": "Лук-шалот" },
    { "ingredientName": "Чеснок" },
    { "ingredientName": "Дижонская горчица" },
    { "ingredientName": "Винный уксус" },
    { "ingredientName": "Черный молотый перец" },
    { "ingredientName": "Базилик" },
    { "ingredientName": "Яйцо" },
    { "ingredientName": "Вода" },
    { "ingredientName": "Свиное сало" },
    { "ingredientName": "Сельдерей" },
    { "ingredientName": "Хлапеньо" },
    { "ingredientName": "Лайм" },
    { "ingredientName": "Морковь" },
    { "ingredientName": "Маса харина пара тамалес" },
    { "ingredientName": "Анчоус" },
    { "ingredientName": "Апельсиновый сок" },
    { "ingredientName": "Растительное масло" },
    { "ingredientName": "Лук" },
    { "ingredientName": "Перец Поблано" },
    { "ingredientName": "Чеснок" },
    { "ingredientName": "Мамалыга" },
    { "ingredientName": "Сладкий картофель" },
    { "ingredientName": "Арахисовое масло" },
    { "ingredientName": "Кукурузный крахмал" },
    { "ingredientName": "Мука" },
    { "ingredientName": "Разрыхлитель" },
    { "ingredientName": "Водка" },
    { "ingredientName": "Цветная капуста" },
    { "ingredientName": "Острый соус" },
    { "ingredientName": "Сливочное масло" },
    { "ingredientName": "Красный перец" },
    { "ingredientName": "Орегано" },
    { "ingredientName": "Петрушка" },
    { "ingredientName": "Багет" },
    { "ingredientName": "Вяленые помидоры" },
    { "ingredientName": "Сыр Моцарелла" },
    { "ingredientName": "Сыр Пармезана-Реджано" },
    { "ingredientName": "Длинные макароны" },
    { "ingredientName": "Сливки" },
    { "ingredientName": "Имбирь" },
    { "ingredientName": "Лимонный сок" },
    { "ingredientName": "Семена черной горчицы" },
    { "ingredientName": "Семена тмина" },
    { "ingredientName": "Куркума" },
    { "ingredientName": "Гарам масала" },
    { "ingredientName": "Кинза" },
    { "ingredientName": "Нут" },
    { "ingredientName": "Сливы" },
    { "ingredientName": "Итальянский баклажан" },
    { "ingredientName": "Огурец" },
    { "ingredientName": "Капуста" },
    { "ingredientName": "Лаваш" },
    { "ingredientName": "Хумус" },
    { "ingredientName": "Соус Тахини" },
    { "ingredientName": "Израильские соленые огурцы" },
    { "ingredientName": "Соус амба" },
    { "ingredientName": "Сыр Пекорино Романо" },
    { "ingredientName": "Рас-эль-ханут" },
    { "ingredientName": "Тофу" },
    { "ingredientName": "Греческий йогурт" },
    { "ingredientName": "Красный лук" },
    { "ingredientName": "Мята" },
    { "ingredientName": "Консервированный лимон" },
    { "ingredientName": "Сумах" },
    { "ingredientName": "Комбу (Морские водоросли)" },
    { "ingredientName": "Кимчи" },
    { "ingredientName": "Соевый соус" },
    { "ingredientName": "Кочукару" },
    { "ingredientName": "Мягкий тофу" },
    { "ingredientName": "Свёкла" },
    { "ingredientName": "Овощной бульон" },
    { "ingredientName": "Сметана" },
    { "ingredientName": "Рис" },
    { "ingredientName": "Кедровые орехи" },
    { "ingredientName": "Морская соль" },
    { "ingredientName": "Тесто для пиццы" },
    { "ingredientName": "Тыква" },
    { "ingredientName": "Мускатный орех" },
    { "ingredientName": "Яблоко" },
    { "ingredientName": "Шалфей" },
    { "ingredientName": "Сыр Грюйер" },
    { "ingredientName": "Коричневая чечевица" },
    { "ingredientName": "Лавровый лист" },
    { "ingredientName": "Баклажан" },
    { "ingredientName": "Розмарин" },
    { "ingredientName": "Перловая крупа" },
    { "ingredientName": "Мирин" },
    { "ingredientName": "Саке" },
    { "ingredientName": "Молотый белый перец" },
    { "ingredientName": "Свиной окорок" },
    { "ingredientName": "Короткозернистый рис" },
    { "ingredientName": "Кизами сега" },
    { "ingredientName": "Свиные ребра" },
    { "ingredientName": "Доенджанга (соевая паста)" },
    { "ingredientName": "Гочугару (корейский порошок чили)" },
    { "ingredientName": "Куриный бульон" },
    { "ingredientName": "Картофель Юкон Голд" },
    { "ingredientName": "Редис" },
    { "ingredientName": "Семена периллы" },
    { "ingredientName": "Чили серрано" },
    { "ingredientName": "Молотый тмин" },
    { "ingredientName": "Сок Лайма" },
    { "ingredientName": "Жареная свиная лопатка" },
    { "ingredientName": "Свиная печень" },
    { "ingredientName": "Субпродукты свиные" },
    { "ingredientName": "Свиная кровь" },
    { "ingredientName": "Корица" },
    { "ingredientName": "Гвоздика" },
    { "ingredientName": "Кокосовый уксус" },
    { "ingredientName": "Клюква" },
    { "ingredientName": "Финики" },
    { "ingredientName": "Грецкий орех" },
    { "ingredientName": "Кешью" },
    { "ingredientName": "Миндаль" },
    { "ingredientName": "Кокосовое масло" },
    { "ingredientName": "Банан" },
    { "ingredientName": "Манго" },
    { "ingredientName": "Ореховое молоко" },
    { "ingredientName": "Орехи макадамия" },
    { "ingredientName": "Кабачки цукини" },
    { "ingredientName": "Помидоры Черри" },
    { "ingredientName": "Семена конопли" },
    { "ingredientName": "Семена подсолнечника" },
    { "ingredientName": "Яблочный уксус" },
    { "ingredientName": "Киви" },
    { "ingredientName": "Клубника" },
    { "ingredientName": "Черника" },
    { "ingredientName": "Вода" },
    { "ingredientName": "Арбуз" },
    { "ingredientName": "Мускусная дыня" },
    { "ingredientName": "Джикама" },
    { "ingredientName": "Персик" },
    { "ingredientName": "Масло агавы" },
    { "ingredientName": "Ванильный экстракт" },
    { "ingredientName": "Вишня" },
    { "ingredientName": "Кокосовая вода" },
    { "ingredientName": "Мед" }
  ]
  
module.exports = ingredients;